# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    body_converter:
        enabled: true
    view:
        formats: { json: true, xml: false, rss: false }
        view_response_listener:  true
    serializer:
        serialize_null: true
    format_listener:
        rules:
           - { path: '^/api', priorities: ['json'], fallback_format: 'json' }
           - { path: '^/', priorities: ['html', '*/*'], fallback_format: html, prefer_extension: true }
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true

#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.

